baseURL = 'https://bfe.one/'
languageCode = 'en-us'
title = 'BitsForEveryone'
theme = 'hugo-bfe'

paginate = 10
summaryLength = 3

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Roster"
    url = "/roster/"
    weight = 4
  [[menu.main]]
    name = "Writeups"
    url = "/writeups/"
    weight = 5

[params]
  TeamName = "Cadet Competitive Cyber Team"
  Description = "The United States Military Academy's premiere competitive cyber team. Organized by instructors, led by cadets, and enabled by West Point's Cyber Research Center."
  BlurbTitle="C3T == BitsForEveryone"
  Blurb="C3T is a team of cadets from the United States Military Academy who are interested in the field of Cyber Security and Cyber Policy. C3T participates in many CTFs and Policy Debates during the academic year as `BitsForEveryone`, including NCX, CCDC, and CSAW. We hack for flags and for country, and are always looking for new members to join our team."
  JoinButton="Join the Discord!"
  ButtonLink="https://www.google.com"
